name: build-linux

on:  workflow_dispatch

env:
  BUILD_TYPE: Debug

jobs:
  build_linux:
   
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.3'
      
    - name: Open superbuild folder
      run: mkdir build

    - name: Configure CMake
      run: |
           cd build 
           cmake ..

    - name: Build
      run: |
           cd build
           make
